---
- name: Determine latest helm version
  register: helm_latest_version
  ansible.builtin.uri:
    url: https://get.helm.sh/helm-latest-version
    return_content: true

- name: Set helm_version
  ansible.builtin.set_fact:
    helm_version: >
      "{{ helm_latest_version.content | regex_replace('(^v|\\n$)', '') }}"
  when: helm_version is not defined

- name: Ensure helm is not installed as an rpm
  ansible.builtin.package:
    name: helm
    state: absent

- name: Install helm client
  notify: Install helm bash completion
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/\
          helm-v{{ helm_latest_version.content | regex_replace('(^v|\\n$)', '') }}-\
          {{ ansible_facts['system'] | lower }}-{{ sys_arch }}.tar.gz"
    dest: "{{ helm_install_dir }}"
    include:
      - "{{ ansible_facts['system'] | lower }}-amd64/helm"
    extra_opts:
      - "--transform"
      - "s/^{{ ansible_facts['system'] | lower }}-amd64\//"
    owner: root
    group: root
    mode: '0755'
    remote_src: true
