---
- name: Set architecture
  ansible.builtin.set_fact:
    sys_arch: "{{ 'amd64' if ansible_facts['architecture'] == 'x86_64' \
      else ansible_facts['architecture'] }}"

- name: Include openshift.yml
  ansible.builtin.include_tasks:
    file: openshift.yml

- name: Include helm.yml
  ansible.builtin.include_tasks:
    file: helm.yml
  when: install_helm

#  - name: Include noobaa tasks
#    ansible.builtin.include_tasks:
#      file: noobaa.yml
#   when: install_noobaa
